# Generated by Django 5.2.17 on 2026-09-18 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(default="Cercle d'Escrime de Founex", max_length=120, verbose_name='Nom du club')),
                ('street', models.CharField(default="[PLACEHOLDER] Rue de l'Escrime 1", max_length=120, verbose_name='Rue et numéro')),
                ('postal_code', models.CharField(default='1297', max_length=16, verbose_name='Code postal')),
                ('city', models.CharField(default='Founex', max_length=80, verbose_name='Ville')),
                ('country', models.CharField(default='CH', max_length=2, verbose_name='Pays (code ISO)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club/', verbose_name='Logo (en-tête des factures)')),
                ('creditor_name', models.CharField(default="[PLACEHOLDER] Cercle d'Escrime de Founex", help_text="Tel qu'il apparaît sur le compte bancaire (max. 70 caractères, norme QR-facture).", max_length=70, verbose_name='Nom du titulaire du compte')),
                ('iban', models.CharField(default='CH4431999123000889012', help_text='Avec un QR-IBAN, une référence QR est générée ; avec un IBAN classique, une référence SCOR.', max_length=34, verbose_name='IBAN ou QR-IBAN')),
                ('treasurer_email', models.EmailField(blank=True, default='tresorier@example.invalid', max_length=254, verbose_name='Email du trésorier (Cc systématique des factures)')),
                ('secretariat_email', models.EmailField(blank=True, default='secretariat@example.invalid', max_length=254, verbose_name="Email du secrétariat (notifications d'inscription)")),
                ('season_start_month', models.PositiveSmallIntegerField(default=9, help_text="9 = septembre. Sert au calcul de la saison courante et des catégories d'âge.", verbose_name='Mois de début de saison')),
                ('invoice_due_days', models.PositiveSmallIntegerField(default=30, verbose_name='Délai de paiement (jours)')),
                ('reminder_delay_days', models.PositiveSmallIntegerField(default=30, help_text="Relance automatique si la facture n'est pas payée après ce délai.", verbose_name='Délai avant relance (jours)')),
                ('invoice_email_subject', models.CharField(default='Cotisation {saison} — {prenom} {nom}', max_length=200, verbose_name="Sujet de l'email de facture")),
                ('invoice_email_body', models.TextField(default="Bonjour,\n\nVous trouverez en pièce jointe la facture de cotisation pour la saison {saison} concernant {prenom} {nom} ({modalite}).\n\nMontant : CHF {montant}\nÉchéance : {echeance}\n\nLa facture comporte une QR-facture que vous pouvez scanner avec votre application bancaire.\n\nAvec nos salutations sportives,\nLe comité du Cercle d'Escrime de Founex", help_text='Variables disponibles : {saison}, {prenom}, {nom}, {modalite}, {montant}, {echeance}, {numero}.', verbose_name="Texte de l'email de facture")),
                ('reminder_email_subject', models.CharField(default='Rappel — cotisation {saison} — {prenom} {nom}', max_length=200, verbose_name="Sujet de l'email de relance")),
                ('reminder_email_body', models.TextField(default="Bonjour,\n\nSauf erreur de notre part, la facture n° {numero} (cotisation {saison}, {prenom} {nom}) d'un montant de CHF {montant}, échue le {echeance}, n'a pas encore été réglée.\n\nVous la trouverez à nouveau en pièce jointe. Si le paiement a été effectué entre-temps, merci de ne pas tenir compte de ce rappel.\n\nAvec nos salutations sportives,\nLe comité du Cercle d'Escrime de Founex", verbose_name="Texte de l'email de relance")),
            ],
            options={
                'verbose_name': 'paramètres du club',
                'verbose_name_plural': 'paramètres du club',
            },
        ),
        migrations.CreateModel(
            name='DashboardNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notes du tableau de bord',
            },
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Tâche')),
                ('is_done', models.BooleanField(default=False, verbose_name='Terminée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos_created', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos_done', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tâche',
                'ordering': ['is_done', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=300)),
                ('action', models.CharField(choices=[('create', 'Création'), ('done', 'Cochée'), ('undone', 'Décochée'), ('edit', 'Modification'), ('delete', 'Suppression')], max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
