# Generated by Django 5.2.17 on 2026-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='auditor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du vérificateur des comptes'),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='president_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du/de la président-e'),
        ),
        migrations.AddField(
            model_name='clubsettings',
            name='vice_president_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email du/de la vice-président-e'),
        ),
    ]
