# Generated by Django 5.2.17 on 2026-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_clubsettings_auditor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubsettings',
            name='invoice_email_body',
            field=models.TextField(default="Bonjour,\n\nVous trouverez en pièce jointe la facture n° {numero} concernant {objet}.\n\nMontant : CHF {montant}\nÉchéance : {echeance}\n\nLa facture comporte une QR-facture que vous pouvez scanner avec votre application bancaire.\n\nAvec nos salutations sportives,\nLe comité du Cercle d'Escrime de Founex", help_text='Variables : {titre}, {objet}, {destinataire}, {numero}, {montant}, {echeance}, {saison}, {prenom}, {nom}, {modalite}. Valable pour les cotisations et les factures manuelles.', verbose_name="Texte de l'email de facture"),
        ),
        migrations.AlterField(
            model_name='clubsettings',
            name='invoice_email_subject',
            field=models.CharField(default='{titre} — {destinataire}', max_length=200, verbose_name="Sujet de l'email de facture"),
        ),
        migrations.AlterField(
            model_name='clubsettings',
            name='reminder_email_body',
            field=models.TextField(default="Bonjour,\n\nSauf erreur de notre part, la facture n° {numero} ({objet}) d'un montant de CHF {montant}, échue le {echeance}, n'a pas encore été réglée.\n\nVous la trouverez à nouveau en pièce jointe. Si le paiement a été effectué entre-temps, merci de ne pas tenir compte de ce rappel.\n\nAvec nos salutations sportives,\nLe comité du Cercle d'Escrime de Founex", verbose_name="Texte de l'email de relance"),
        ),
        migrations.AlterField(
            model_name='clubsettings',
            name='reminder_email_subject',
            field=models.CharField(default='Rappel — {titre} — {destinataire}', max_length=200, verbose_name="Sujet de l'email de relance"),
        ),
    ]
