# Generated by Django 5.2.17 on 2026-10-08 15:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_generic_invoice_email_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsettings',
            name='trial_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text="Montant fixe facturé pour un cours d'essai, quel que soit le cours.", max_digits=8, verbose_name="Tarif du cours d'essai (CHF)"),
        ),
    ]
