# Generated by Django 5.2.17 on 2026-09-18 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Ordre')),
                ('is_course', models.BooleanField(default=False, help_text='Cochez pour les groupes correspondant à un créneau de cours.', verbose_name='Groupe de cours')),
            ],
            options={
                'verbose_name': 'groupe',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True, verbose_name='Clé technique')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('field_type', models.CharField(choices=[('TEXT', 'Texte court'), ('TEXTAREA', 'Texte long'), ('EMAIL', 'Email'), ('PHONE', 'Téléphone'), ('DATE', 'Date'), ('SELECT', 'Liste déroulante (choix unique)'), ('MULTISELECT', 'Sélecteur multiple'), ('WEEKDAYS', 'Jours de la semaine'), ('BOOLEAN', 'Case à cocher (oui/non)'), ('NUMBER', 'Nombre')], default='TEXT', max_length=12, verbose_name='Type')),
                ('choices', models.JSONField(blank=True, default=list, help_text='Pour les listes : une option par ligne.', verbose_name='Options')),
                ('profiles', models.JSONField(blank=True, default=list, help_text='Liste parmi MINEUR, MAJEUR, ESSAI (vide = tous).', verbose_name='Profils concernés')),
                ('is_builtin', models.BooleanField(default=False, editable=False, verbose_name='Champ natif')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Masquée par défaut dans les listes et exclue des exports par défaut.', verbose_name='Donnée sensible')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.PositiveSmallIntegerField(default=500, verbose_name='Ordre')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='Aide')),
            ],
            options={
                'verbose_name': 'champ de fiche',
                'verbose_name_plural': 'champs de fiche',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TariffBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nom')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'tranche tarifaire',
                'verbose_name_plural': 'tranches tarifaires',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nom')),
                ('days_per_week', models.PositiveSmallIntegerField(default=1, verbose_name='Jours par semaine')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': "modalité d'entraînement",
                'verbose_name_plural': "modalités d'entraînement",
                'ordering': ['sort_order', 'days_per_week'],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
                ('columns', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.contactgroup')),
            ],
            options={
                'verbose_name': 'vue enregistrée',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('MINEUR', 'Mineur'), ('MAJEUR', 'Majeur'), ('ESSAI', "Cours d'essai")], default='MAJEUR', max_length=10, verbose_name='Profil')),
                ('kind', models.CharField(choices=[('PERSONNE', 'Personne'), ('ENTREPRISE', 'Entreprise')], default='PERSONNE', max_length=12, verbose_name='Type de contact')),
                ('company_name', models.CharField(blank=True, max_length=120, verbose_name='Raison sociale')),
                ('title', models.CharField(blank=True, choices=[('MONSIEUR', 'Monsieur'), ('MADAME', 'Madame'), ('FAMILLE', 'Famille'), ('AUX_PARENTS', 'Aux parents de')], max_length=12, verbose_name='Titre')),
                ('first_name', models.CharField(max_length=80, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=80, verbose_name='Nom')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='Adresse')),
                ('postal_code', models.CharField(blank=True, max_length=16, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='Ville')),
                ('country', models.CharField(blank=True, choices=[('CH', 'Suisse'), ('FR', 'France'), ('DE', 'Allemagne'), ('IT', 'Italie'), ('AT', 'Autriche'), ('LI', 'Liechtenstein'), ('BE', 'Belgique'), ('LU', 'Luxembourg'), ('NL', 'Pays-Bas'), ('ES', 'Espagne'), ('PT', 'Portugal'), ('GB', 'Royaume-Uni'), ('IE', 'Irlande'), ('US', 'États-Unis'), ('CA', 'Canada'), ('BR', 'Brésil'), ('RU', 'Russie'), ('UA', 'Ukraine'), ('PL', 'Pologne'), ('CZ', 'Tchéquie'), ('HU', 'Hongrie'), ('RO', 'Roumanie'), ('GR', 'Grèce'), ('TR', 'Turquie'), ('SE', 'Suède'), ('NO', 'Norvège'), ('DK', 'Danemark'), ('FI', 'Finlande'), ('CN', 'Chine'), ('JP', 'Japon'), ('KR', 'Corée du Sud'), ('IN', 'Inde'), ('AU', 'Australie'), ('MA', 'Maroc'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('EG', 'Égypte'), ('ZA', 'Afrique du Sud'), ('AR', 'Argentine'), ('MX', 'Mexique'), ('XX', 'Autre')], default='CH', max_length=2, verbose_name='Pays')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('AUTRE', 'Autre')], max_length=6, verbose_name='Sexe')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('nationality', models.CharField(blank=True, choices=[('CH', 'Suisse'), ('FR', 'Française'), ('DE', 'Allemande'), ('IT', 'Italienne'), ('AT', 'Autrichienne'), ('LI', 'Liechtensteinoise'), ('BE', 'Belge'), ('LU', 'Luxembourgeoise'), ('NL', 'Néerlandaise'), ('ES', 'Espagnole'), ('PT', 'Portugaise'), ('GB', 'Britannique'), ('IE', 'Irlandaise'), ('US', 'Américaine'), ('CA', 'Canadienne'), ('BR', 'Brésilienne'), ('RU', 'Russe'), ('UA', 'Ukrainienne'), ('PL', 'Polonaise'), ('CZ', 'Tchèque'), ('HU', 'Hongroise'), ('RO', 'Roumaine'), ('GR', 'Grecque'), ('TR', 'Turque'), ('SE', 'Suédoise'), ('NO', 'Norvégienne'), ('DK', 'Danoise'), ('FI', 'Finlandaise'), ('CN', 'Chinoise'), ('JP', 'Japonaise'), ('KR', 'Sud-coréenne'), ('IN', 'Indienne'), ('AU', 'Australienne'), ('MA', 'Marocaine'), ('TN', 'Tunisienne'), ('DZ', 'Algérienne'), ('EG', 'Égyptienne'), ('ZA', 'Sud-africaine'), ('AR', 'Argentine'), ('MX', 'Mexicaine'), ('XX', 'Autre')], max_length=2, verbose_name='Nationalité')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Entrée')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Sortie')),
                ('status', models.CharField(choices=[('ACTIF', 'Actif'), ('LICENCE', 'Licence uniquement'), ('ESSAI', 'Essai'), ('EN_ATTENTE', 'En attente de validation'), ('INACTIF', 'Inactif / sorti')], default='EN_ATTENTE', max_length=12, verbose_name='Statut')),
                ('member_id', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='Ex. Direction, Comité, Entraîneur…', max_length=80, verbose_name='Rôle')),
                ('avs_number', models.CharField(blank=True, help_text='Format 756.XXXX.XXXX.XX', max_length=16, verbose_name='N° AVS')),
                ('laterality', models.CharField(blank=True, choices=[('DROITE', 'Droite'), ('GAUCHE', 'Gauche')], max_length=6, verbose_name='Latéralité')),
                ('licence_number', models.CharField(blank=True, max_length=40, verbose_name='N° de licence')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone élève')),
                ('phone_parent1', models.CharField(blank=True, max_length=30, verbose_name='Téléphone parent 1')),
                ('phone_parent2', models.CharField(blank=True, max_length=30, verbose_name='Téléphone parent 2')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('email_alt', models.EmailField(blank=True, max_length=254, verbose_name='Email alternative')),
                ('email_parent1', models.EmailField(blank=True, max_length=254, verbose_name='Email parent 1')),
                ('email_parent2', models.EmailField(blank=True, max_length=254, verbose_name='Email parent 2')),
                ('training_days', models.JSONField(blank=True, default=list, verbose_name="Jours d'entraînement")),
                ('family_discount', models.BooleanField(default=False, help_text='-100 CHF sur la cotisation. Cochée par le comité à la validation.', verbose_name='Réduction famille (2ᵉ enfant et suivants)')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques internes')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Champs personnalisés')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='members', to='members.contactgroup', verbose_name='Groupes')),
                ('tariff_bracket', models.ForeignKey(blank=True, help_text="Complétée par le comité à la validation de l'inscription.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.tariffbracket', verbose_name='Tranche tarifaire')),
                ('training_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.trainingmode', verbose_name="Modalité d'entraînement")),
            ],
            options={
                'verbose_name': 'contact',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='UserListPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
