# Generated by Django 5.2.17 on 2026-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddefinition',
            name='layout',
            field=models.JSONField(blank=True, default=dict, help_text='Personnalisation par profil : {PROFIL: {label, section, order}}. Modifiée depuis « Modèle des fiches ».', verbose_name='Mise en page par profil'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='section',
            field=models.CharField(blank=True, max_length=12, verbose_name='Section par défaut'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('TIREUR', 'Tireur-euse'), ('COACH', 'Coach'), ('MAITRE_ARMES', "Maître d'arme"), ('MEMBRE', 'Membre'), ('COMITE', 'Comité'), ('PRESIDENT', 'Président-e'), ('VICE_PRESIDENT', 'Vice-président-e'), ('TRESORIER', 'Trésorier-ère'), ('SECRETAIRE', 'Secrétaire'), ('VERIFICATEUR', 'Vérificateur des comptes')], max_length=16, verbose_name='Rôle'),
        ),
    ]
