# Generated by Django 5.2.17 on 2026-09-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_group_public_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddefinition',
            name='profiles',
            field=models.JSONField(blank=True, default=list, help_text='Liste parmi MINEUR, MAJEUR, ESSAI.', verbose_name='Profils concernés'),
        ),
    ]
