# Generated by Django 5.2.17 on 2026-09-18 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('slug', models.SlugField(help_text='Fin du lien public : /formulaires/public/<adresse>/', max_length=80, unique=True, verbose_name='Adresse publique')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif (accessible publiquement)')),
                ('profile', models.CharField(choices=[('MINEUR', 'Mineur'), ('MAJEUR', 'Majeur'), ('ESSAI', "Cours d'essai")], default='MAJEUR', help_text="Profil par défaut ; un champ « Type d'inscription » dans le formulaire peut le remplacer selon la réponse.", max_length=10, verbose_name='Profil de fiche créé')),
                ('intro_text', models.TextField(blank=True, verbose_name="Texte d'introduction")),
                ('privacy_notice', models.TextField(default="Les données saisies sont utilisées exclusivement par le comité du Cercle d'Escrime de Founex pour la gestion des inscriptions, des cours, des licences et de la facturation des cotisations. Elles ne sont transmises à aucun tiers en dehors des obligations liées à la licence fédérale. Vous pouvez demander leur consultation, correction ou suppression en écrivant au secrétariat du club.", verbose_name='Mention de protection des données (LPD)')),
                ('success_message', models.TextField(default='Merci ! Votre inscription a bien été transmise au comité, qui la validera prochainement et reviendra vers vous.', verbose_name='Message de confirmation')),
                ('notify_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de notification (vide = secrétariat des paramètres)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('default_groups', models.ManyToManyField(blank=True, to='members.contactgroup', verbose_name='Groupes attribués automatiquement')),
            ],
            options={
                'verbose_name': 'formulaire',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('FIELD', 'Champ de la fiche membre'), ('TEXT', 'Bloc de texte explicatif'), ('PROFILE', "Type d'inscription (Mineur / Majeur)")], default='FIELD', max_length=8)),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Libellé affiché (vide = libellé de la fiche)')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='Aide')),
                ('text', models.TextField(blank=True, verbose_name='Texte du bloc')),
                ('required', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('condition_operator', models.CharField(blank=True, choices=[('eq', 'est égal à'), ('ne', 'est différent de'), ('notempty', 'est renseigné'), ('contains', 'contient')], default='eq', max_length=10)),
                ('condition_value', models.CharField(blank=True, max_length=150, verbose_name='Valeur')),
                ('condition_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='formbuilder.formfield', verbose_name='Afficher si le champ')),
                ('field_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.fielddefinition')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formbuilder.formdefinition')),
            ],
            options={
                'verbose_name': 'champ de formulaire',
                'verbose_name_plural': 'champs de formulaire',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=120)),
                ('data', models.JSONField(default=list, verbose_name='Réponses')),
                ('profile', models.CharField(choices=[('MINEUR', 'Mineur'), ('MAJEUR', 'Majeur'), ('ESSAI', "Cours d'essai")], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('notify_error', models.TextField(blank=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='formbuilder.formdefinition')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='members.member')),
            ],
            options={
                'verbose_name': 'soumission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
