# Generated by Django 5.2.17 on 2026-09-18 22:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Numéro')),
                ('season', models.CharField(max_length=9, verbose_name='Saison')),
                ('training_mode_label', models.CharField(blank=True, max_length=80, verbose_name='Modalité')),
                ('bracket_label', models.CharField(blank=True, max_length=80, verbose_name='Tranche')),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant de base')),
                ('family_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Réduction famille')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant')),
                ('description', models.CharField(max_length=140, verbose_name='Motif')),
                ('debtor_name', models.CharField(max_length=70)),
                ('debtor_street', models.CharField(blank=True, max_length=70)),
                ('debtor_postal_code', models.CharField(blank=True, max_length=16)),
                ('debtor_city', models.CharField(blank=True, max_length=35)),
                ('debtor_country', models.CharField(default='CH', max_length=2)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email destinataire')),
                ('reference', models.CharField(blank=True, max_length=27, verbose_name='Référence de paiement')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name='Échéance')),
                ('status', models.CharField(choices=[('GENEREE', 'Générée (non envoyée)'), ('ENVOYEE', 'Envoyée'), ('RELANCEE', 'Relancée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='GENEREE', max_length=10, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('reminded_at', models.DateTimeField(blank=True, null=True, verbose_name='Relancée le')),
                ('reminder_count', models.PositiveSmallIntegerField(default=0, verbose_name='Nombre de relances')),
                ('paid_at', models.DateField(blank=True, null=True, verbose_name='Payée le')),
                ('pdf', models.FileField(blank=True, upload_to='factures/%Y/', verbose_name='PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.storedfile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='members.member')),
                ('paid_marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_marked_paid', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'facture',
                'ordering': ['-issue_date', '-number'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('facture', 'Facture'), ('relance', 'Relance'), ('mailing', 'Mailing'), ('notification', 'Notification')], max_length=14)),
                ('to', models.CharField(max_length=300)),
                ('cc', models.CharField(blank=True, max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='members.member')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'email envoyé',
                'verbose_name_plural': 'emails envoyés',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('season', models.CharField(max_length=9, verbose_name='Saison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_description', models.CharField(blank=True, max_length=200, verbose_name='Source')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lot de factures',
                'verbose_name_plural': 'lots de factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.invoicebatch'),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant (CHF)')),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='members.tariffbracket')),
                ('training_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='members.trainingmode')),
            ],
            options={
                'verbose_name': 'tarif',
                'unique_together': {('training_mode', 'bracket')},
            },
        ),
    ]
