# Generated by Django 5.2.17 on 2026-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('COTISATION', 'Cotisation'), ('MANUELLE', 'Facture manuelle')], default='COTISATION', max_length=12, verbose_name='Type'),
        ),
    ]
