# Generated by Django 5.2.17 on 2026-10-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='kind',
            field=models.CharField(choices=[('COTISATION', 'Cotisation'), ('ESSAI', "Cours d'essai"), ('MANUELLE', 'Facture manuelle')], default='COTISATION', max_length=12, verbose_name='Type'),
        ),
    ]
