# Generated by Django 5.2.17 on 2026-10-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_invoice_kind'),
        ('members', '0007_alter_fielddefinition_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='members.member'),
        ),
    ]
