# Generated by Django 5.2.17 on 2026-10-08 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0007_alter_fielddefinition_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonRollover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_season', models.CharField(max_length=9, verbose_name='Saison préparée')),
                ('subject', models.CharField(max_length=200, verbose_name="Sujet de l'email")),
                ('body', models.TextField(verbose_name="Texte de l'email")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'passage de saison',
                'verbose_name_plural': 'passages de saison',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RenewalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=160, verbose_name='Membre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email utilisé')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(verbose_name="Lien valable jusqu'au")),
                ('status', models.CharField(choices=[('SENT', 'Invitation envoyée — sans réponse'), ('TO_VALIDATE', 'Données envoyées — à valider'), ('RESIGNATION', 'Démission annoncée — à confirmer'), ('VALIDATED', 'Données validées'), ('RESIGNED', 'Démission confirmée — fiche supprimée'), ('KEPT', 'Démission non confirmée — fiche conservée'), ('FAILED', 'Envoi impossible')], default='SENT', max_length=12, verbose_name='Statut')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_error', models.TextField(blank=True)),
                ('proposed', models.JSONField(blank=True, default=dict, verbose_name='Valeurs modifiées')),
                ('changes', models.JSONField(blank=True, default=list, verbose_name='Changements (affichage)')),
                ('remark', models.TextField(blank=True, verbose_name='Remarque du membre')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_requests', to='members.member')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rollover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='renewals.seasonrollover')),
            ],
            options={
                'verbose_name': 'réponse de passage de saison',
                'verbose_name_plural': 'réponses de passage de saison',
                'ordering': ['member_name'],
                'constraints': [models.UniqueConstraint(fields=('rollover', 'member'), name='one_request_per_member_and_rollover')],
            },
        ),
    ]
