# Generated by Django 5.2.17 on 2026-09-18 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('kind', models.CharField(choices=[('DYNAMIC', 'Dynamique (suit un groupe)'), ('STATIC', 'Statique (sélection figée)')], default='DYNAMIC', max_length=8, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.contactgroup', verbose_name='Groupe suivi')),
                ('static_members', models.ManyToManyField(blank=True, related_name='mailing_lists', to='members.member', verbose_name='Contacts')),
            ],
            options={
                'verbose_name': 'liste de diffusion',
                'verbose_name_plural': 'listes de diffusion',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('body', models.TextField(verbose_name='Message')),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('errors_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, upload_to='mailing/%Y/', verbose_name='Pièce jointe')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailinglist')),
            ],
            options={
                'verbose_name': 'envoi groupé',
                'verbose_name_plural': 'envois groupés',
                'ordering': ['-sent_at'],
            },
        ),
    ]
