# Generated by Django 5.2.17 on 2026-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='billing_rule',
            field=models.CharField(blank=True, choices=[('MEMBERSHIP', 'Inscriptions définitives à facturer'), ('TRIAL', "Cours d'essai à facturer")], help_text='Uniquement pour les deux listes système « à facturer ».', max_length=10, verbose_name='Règle (listes automatiques)'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='kind',
            field=models.CharField(choices=[('DYNAMIC', 'Dynamique (suit un groupe)'), ('STATIC', 'Statique (sélection figée)'), ('BILLING', 'Automatique (à facturer)')], default='DYNAMIC', max_length=8, verbose_name='Type'),
        ),
    ]
